set(PROJECT_NAME "MultiMiner")
set(PROJECT_VER_MAJOR "4")
set(PROJECT_VER_MINOR "0-pr1")
set(PROJECT_ASCII_LOGO " _____     _ _   _ _____ _\\n|     |_ _| | |_|_|     |_|___ ___ ___\\n| | | | | | |  _| | | | | |   | -_|  _|\\n|_|_|_|___|_|_| |_|_|_|_|_|_|_|___|_|  ")
set(PROJECT_URL "http://multiminerapp.com")
set(PROJECT_URL_DOWNLOAD "http://releases.multiminerapp.com")
set(PROJECT_COPYRIGHT "(C) 2013-2014")
set(PROJECT_LICENSE "GPL3")
set(PROJECT_LICENSE_TEXT "${PROJECT_NAME} is free software; you can redistribute it and/or modify\\nit under the terms of the GNU General Public License as published by\\nthe Free Software Foundation; either version 3 of the License, or\\n(at your option) any later version.\\n\\n${PROJECT_NAME} is distributed in the hope that it will be useful,\\nbut WITHOUT ANY WARRANTY; without even the implied warranty of\\nMERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\\nGNU General Public License for more details.\\n\\nYou should have received a copy of the GNU General Public License\\nalong with ${PROJECT_NAME}.  If not, see <http://www.gnu.org/licenses/>.")
set(PROJECT_AUTHOR "Nathanial Woolls")
set(PROJECT_AUTHOR_EMAIL "nwoolls@gmail.com")
